"""Export a backtest result as an Obsidian-friendly markdown note.

The vault is just a folder of markdown. Path resolution order:
  1. explicit `vault_path` argument
  2. QUANT_VAULT_PATH env var
  3. ./vault next to this app (default scaffold, checked in)

Notes land in <vault>/Backtests/ with YAML front-matter so Obsidian can index
them by symbol/timeframe/strategy/status. Every note carries the funding-gap
caveat and the not-financial-advice boundary. We never overwrite silently:
each file is timestamped to the minute and de-duplicated with a suffix.
"""
from __future__ import annotations

import datetime as _dt
import os
from pathlib import Path
from typing import Dict, List, Optional

from .engine import BacktestResult

APP_DIR = Path(__file__).resolve().parent.parent
DEFAULT_VAULT = APP_DIR / "vault"


def resolve_vault(vault_path: Optional[str] = None) -> Path:
    p = vault_path or os.getenv("QUANT_VAULT_PATH") or str(DEFAULT_VAULT)
    return Path(p).expanduser()


def _utc_now() -> _dt.datetime:
    return _dt.datetime.now(_dt.timezone.utc)


def _fmt_ms(ms: int) -> str:
    return _dt.datetime.fromtimestamp(ms / 1000, _dt.timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC")


def _pct(x: float) -> str:
    return f"{x * 100:+.2f}%"


def _sparkline(values: List[float], width: int = 60) -> str:
    """Unicode block sparkline of the equity curve (no external deps)."""
    if not values:
        return ""
    blocks = "▁▂▃▄▅▆▇█"
    if len(values) > width:
        step = len(values) / width
        sampled = [values[int(i * step)] for i in range(width)]
    else:
        sampled = list(values)
    lo, hi = min(sampled), max(sampled)
    span = hi - lo or 1.0
    return "".join(blocks[min(7, int((v - lo) / span * 7))] for v in sampled)


def _metrics_table(m_is: Dict[str, float], m_oos: Dict[str, float]) -> str:
    rows = [
        ("Total return", _pct(m_is.get("return", 0)), _pct(m_oos.get("return", 0))),
        ("CAGR (24/7 ann.)", _pct(m_is.get("cagr", 0)), _pct(m_oos.get("cagr", 0))),
        ("Sharpe", f"{m_is.get('sharpe', 0):.2f}", f"{m_oos.get('sharpe', 0):.2f}"),
        ("Max drawdown", _pct(m_is.get("max_drawdown", 0)), _pct(m_oos.get("max_drawdown", 0))),
        ("Trades (round-trips)", f"{int(m_is.get('n_trades', 0))}", "—"),
        ("Win rate", _pct(m_is.get("win_rate", 0)), "—"),
        ("Exposure", _pct(m_is.get("exposure", 0)), _pct(m_oos.get("exposure", 0))),
        ("Bars", f"{int(m_is.get('n_bars', 0))}", f"{int(m_oos.get('n_bars', 0))}"),
    ]
    out = ["| Metric | IS (holdout train) | OOS (holdout test) |",
           "| --- | --- | --- |"]
    for name, a, b in rows:
        out.append(f"| {name} | {a} | {b} |")
    return "\n".join(out)


def render_markdown(result: BacktestResult, notes: str = "") -> str:
    r = result
    created = _utc_now()
    sharpe_oos = r.metrics_oos.get("sharpe", 0.0)
    bug_flag = "\n> ⚠️ OOS Sharpe > 3 — treat as a likely bug, not an edge." \
        if sharpe_oos > 3 else ""
    fm = [
        "---",
        "type: backtest",
        f"symbol: {r.symbol}",
        f"timeframe: {r.interval}",
        f"strategy: {r.strategy}",
        f"status: {r.status}",
        f"created: {created.strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"bars: {r.n_bars}",
        f"funding_modeled: {str(r.funding_modeled).lower()}",
        f"tags: [backtest, hyperliquid, {r.strategy}]",
        "---",
    ]
    params = "\n".join(f"| {k} | {v} |" for k, v in r.params.items()) or "| — | — |"
    body = f"""
# Backtest — {r.symbol} {r.interval} · {r.strategy}

> Not financial advice. Research artifact only. Status: **{r.status}**.
> Funding is **not modeled** (engine gap) — perps results are incomplete.{bug_flag}

## Data
- Source: MoonDev candles API (real OHLCV) or supplied real CSV.
- Bars: **{r.n_bars}**
- Range: {_fmt_ms(r.start_ms)} → {_fmt_ms(r.end_ms)}

## Parameters
| key | value |
| --- | --- |
{params}

## Costs
- Taker fee: {r.fee_bps:.2f} bps
- Slippage: {r.slippage_bps:.2f} bps (vol-scaled per bar)
- Cost multiplier: {r.cost_mult:.1f}x

## Metrics
{_metrics_table(r.metrics_is, r.metrics_oos)}

_IS/OOS here is a simple chronological holdout for honesty, **not**
walk-forward validation. Promote nothing on this alone._

## Equity curve (full sample, starts at 1.0)
```
{_sparkline(r.equity_curve)}
final equity: {r.equity_curve[-1]:.4f}   ({_pct(r.equity_curve[-1] - 1.0)})
```

## Notes
{notes.strip() or "_(none)_"}

---
*Generated by hl-quant-dashboard. Re-run at 2x costs before taking anything
seriously, and validate with proper walk-forward + permutation tests.*
"""
    return "\n".join(fm) + "\n" + body


def _slugify(*parts: str) -> str:
    s = "-".join(str(p) for p in parts)
    return "".join(ch if ch.isalnum() or ch in "-_" else "-" for ch in s).strip("-")


def export(result: BacktestResult, *, notes: str = "",
           vault_path: Optional[str] = None) -> Path:
    """Write the note and return its path. Creates the vault dir if needed."""
    vault = resolve_vault(vault_path)
    bt_dir = vault / "Backtests"
    bt_dir.mkdir(parents=True, exist_ok=True)
    stamp = _utc_now().strftime("%Y%m%d-%H%M")
    base = _slugify(result.symbol, result.interval, result.strategy, stamp)
    target = bt_dir / f"{base}.md"
    n = 1
    while target.exists():
        target = bt_dir / f"{base}-{n}.md"
        n += 1
    target.write_text(render_markdown(result, notes), encoding="utf-8")
    return target
